name: Auto filling pull request
on:

  pull_request:
    branches: [main]
    types:
      - "opened"


  workflow_dispatch:
jobs:
  auto-filling-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Labeler
        uses: actions/labeler@v4
        with:
          repo-token: "${{ secrets.PAT }}"
          configuration-path: ".github/labeler.yml"
          
      - name: automerge
        uses: "pascalgn/automerge-action@v0.14.3"
        env:
          GITHUB_TOKEN: "${{ secrets.PAT }}"
          MERGE_LABELS: "automerge,!work in progress"
          MERGE_REMOVE_LABELS: ""
          MERGE_METHOD: "squash"
          MERGE_COMMIT_MESSAGE: "pull-request-description"
          MERGE_FORKS: "false"
          MERGE_RETRIES: "1"
          MERGE_RETRY_SLEEP: "10000"
          MERGE_REQUIRED_APPROVALS: "0"
          UPDATE_LABELS: ""
          UPDATE_METHOD: "merge"
          #PULL_REQUEST: "1"
