name: Auto filling pull request
on:
  pull_request:
    types: [opened]
  workflow_dispatch:
jobs:
  auto-filling-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Add labels based on PR title
        uses: jackwener/set-label-based-on-pr-title@v1
        with:
          words: >-
            Update;
            from;
            dev
          labels: >-
            automerge;
            release;
            done
          repo-token: "${{ secrets.PAT }}"
