name: .NET

on:
  
  pull_request:
    branches: [ main, test, dev, qa ]
  
  workflow_dispatch:
    
jobs:
  Checkout-and-Build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
     
    - uses: reitermarkus/automerge@v2
      with:
        token: ${{ secrets.MY_GITHUB_TOKEN }}
        merge-method: rebase
        do-not-merge-labels: never-merge
        required-labels: automerge
        pull-request: ${{ github.event.inputs.pull-request }}
        dry-run: true
