name: .NET

on:
  push:
    branches: [dev]

  workflow_dispatch:

jobs:
  Checkout-and-Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Get changed files using a comma separator
        id: changed-files
        uses: tj-actions/changed-files@v17.3       

      - name: List all changed files
        run: |
          dest=""         
          for file in ${{ steps.changed-files.outputs.all_changed_and_modified_files }}; 
          do
          dest+="${file}\n"          
          done
          echo All_Files=$dest >> $GITHUB_ENV
          echo destin: $dest

      - name: Create Pull Request with CURL
        run: 'curl -X POST --header "Authorization: token ${{secrets.PAT}}" -d "{\"title\":\"Automated Pull Request From dev Branch\",\"body\": \"${{env.All_Files}}\",\"head\": \"dev\",\"base\": \"main\"}" https://api.github.com/repos/vamsea2002/win/pulls'
