name: .NET

on:
  push:
    branches: [dev]

  workflow_dispatch:

jobs:
  Checkout-and-Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Get changed files using a comma separator
        id: changed-files
        uses: tj-actions/changed-files@v17.3
        with:
          separator: "\n"

      - name: List all changed files
        run: |          
          echo All Changed files list: ${{ steps.changed-files.outputs.all_changed_and_modified_files }}
          echo lst = ${{ steps.changed-files.outputs.all_changed_and_modified_files }};
          echo "All_Files=$lst" >> $GITHUB_ENV


      - name: Create Pull Request with CURL
        run: 'curl -X POST --header "Authorization: token ${{secrets.PAT}}" -d "{\"title\":\"Automated Pull Request From dev Branch\",\"body\": \"{{env.All_Files}}\",\"head\": \"dev\",\"base\": \"main\"}" https://api.github.com/repos/vamsea2002/win/pulls'
