name: .NET

on:
  push:
    branches: [ test, dev, qa ]  
  pull_request: 
   branches: [main]
   
  workflow_dispatch:
    
jobs:
  checkout-dotnet:
   if: github.event_name == 'pull_request'
   runs-on: ubuntu-latest
   steps:
    - uses: actions/checkout@v3.0.0

  automerge:
    if: github.event.review.state == 'approved' || !github.event.review
    runs-on: ubuntu-latest
    steps:
      - uses: reitermarkus/automerge@v1.5.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          merge-method: merge
          do-not-merge-labels: never-merge
          required-labels: automerge
          pull-request: ${{ github.event.inputs.pull-request }}
          dry-run: false
