name: .NET

on:
  push:
    branches: [ main, test, dev, qa ]  
  
  workflow_dispatch:
    
jobs:
  Checkout-and-Build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
     
  automerge:
    if: github.event.review.state == 'approved' || !github.event.review
    runs-on: ubuntu-latest
    steps:
      - uses: reitermarkus/automerge@v1.5.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          merge-method: rebase
          do-not-merge-labels: never-merge
          required-labels: automerge
          pull-request: ${{ github.event.inputs.pull-request }}
          dry-run: false
