name: .NET

on:
  push:
    branches: [dev]

  workflow_dispatch:

jobs:
  Checkout-and-Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create pull Request
        if: github.ref == 'refs/heads/dev'
        uses: TheRealWaldo/pull-request@v0.2.0
        env:
         GITHUB_TOKEN: ${{secrets.PAT}}
        with:
         title: Automated Pull Request From dev Branch
         base: master
         head: dev
         assignee: vamsea2020
         body: Automated Pull Request From dev Branch
