name: .NET

on:
  push:
    branches: [ main, test ]
  pull_request:
    branches: [ main, test ]
  
  workflow_dispatch:
    

jobs:
  Checkout-and-Build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
     
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Run
      run: dotnet bin\Debug\net6.0\PrintMsg.dll
  
  Auto-pull-request:
    needs: Checkout-and-Build
    runs-on: windows-latest

    steps:
     - name: Create Pull Request
       uses: peter-evans/create-pull-request@v3
       with:
        branch: test
        base: main 
        title: An Automated pull request
        committer: vamsea2002
        author: vamsea2002
        body: This is automated
        token: ${{secrets.GITHUB_TOKEN}}
        delete-branch: false
