name: .NET

on:
  
  pull_request:
    branches: [ main, test, dev, qa ]
  
  workflow_dispatch:
    
jobs:
  Checkout-and-Build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
     
    - uses: gr2m/create-or-update-pull-request-action@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        title: "My pull request title"
        body: "My pull request body"
        branch: "main"
        path: "*"
        commit-message: "My commit message for uncommitted changes in lib/ folder"
        author: "vamsea2002"
        labels: label1, label2
        assignees: vamsea2002, vamsea2020
        reviewers: vamsea2002, vamsea2020
        team_reviewers: vamsea2002, vamsea2020
        auto-merge: merge
        update-pull-request-title-and-body: true
